Object.assign(EXAM_DATA, {
  "Platform User Experience Designer": {
    questions: 60,
    time: 105,
    pass: "65%",
    experience: "2+ years",
    trailheadUrl: "https://trailheadacademy.salesforce.com/certificate/exam-ux-designer---Plat-UX-101",
    prerequisites: [
      {name:"Platform Administrator",url:"https://trailhead.salesforce.com/content/learn/trails/force_com_admin_intermediate",note:"Admin knowledge of page layouts, components, and app configuration is assumed throughout the exam."}
    ],
    overview: "The Platform User Experience Designer certification validates your ability to design intuitive, accessible, and user-centred experiences on the Salesforce platform. The exam covers UX research methods, Lightning Design System, information architecture, prototyping, and accessibility standards — all applied specifically to Salesforce Lightning applications.",
    domains: [
      {name:"Discovery",pct:18,color:"#00A1E0",desc:"Plan and execute UX research to understand user needs before designing solutions.",keyTopics:[
        {title:"User Research Methods",desc:"Interviews, surveys, contextual inquiry, and usability testing each serve different purposes — choose the right method based on what you need to learn and when in the project."},
        {title:"Journey Mapping",desc:"Customer and user journey maps visualize the end-to-end experience across touchpoints, revealing pain points and opportunities that are invisible in system-level requirements."},
        {title:"Persona Development",desc:"Personas synthesize research into representative user archetypes — use them to build empathy and keep design decisions grounded in real user goals and behaviours."},
        {title:"Stakeholder Alignment",desc:"UX designers must align business goals with user needs — discovery outputs (research findings, personas, journey maps) should be shared artifacts, not private documents."}
      ]},
      {name:"UX Fundamentals",pct:17,color:"#2ECC71",desc:"Apply core UX principles — information architecture, interaction design, and visual hierarchy — to Salesforce solutions.",keyTopics:[
        {title:"Information Architecture",desc:"Organize content and navigation so users can find what they need quickly — apply IA principles to Lightning app navigation, record layouts, and list views."},
        {title:"Visual Hierarchy",desc:"Use size, colour, contrast, and spacing to guide user attention to the most important elements on a page — on Salesforce, this maps to component placement and page layout choices."},
        {title:"Interaction Design Principles",desc:"Affordances, feedback, consistency, and error prevention are the pillars of good interaction design — apply them when configuring flows, buttons, and custom components."},
        {title:"Progressive Disclosure",desc:"Show only the information users need at each step — hide complexity behind detail panels, tabs, and related lists rather than overwhelming users with everything at once."}
      ]},
      {name:"Salesforce Lightning Design System",pct:25,color:"#F39C12",desc:"Use SLDS guidelines, components, and tokens to build consistent, on-brand Salesforce experiences.",keyTopics:[
        {title:"SLDS Components",desc:"SLDS provides a library of pre-built, accessible components (buttons, cards, forms, badges) — use them in LWC and Aura components to maintain visual consistency with the platform."},
        {title:"Design Tokens",desc:"SLDS design tokens are named variables for visual properties (colours, spacing, font sizes) — using tokens instead of hardcoded values ensures designs stay consistent when themes change."},
        {title:"Utility Classes",desc:"SLDS utility classes apply spacing, alignment, and typography without custom CSS — they enforce consistent styling across components built by different developers."},
        {title:"Component Blueprints",desc:"SLDS blueprints are HTML/CSS reference implementations for components — use them as the source of truth when building custom components to ensure accessibility and visual consistency."},
        {title:"SLDS Icons",desc:"Use the SLDS icon library (standard, utility, action, custom) with correct category and sizing — icons must include assistive text for screen reader accessibility."}
      ]},
      {name:"Prototyping",pct:12,color:"#E74C3C",desc:"Create low- and high-fidelity prototypes to communicate design intent and validate solutions with users.",keyTopics:[
        {title:"Fidelity Levels",desc:"Low-fidelity wireframes test structure and flow cheaply; high-fidelity prototypes test visual design and micro-interactions — match fidelity to the design question you are answering."},
        {title:"Prototyping Tools",desc:"Figma, Sketch, Adobe XD, and InVision are common tools — for Salesforce-specific prototyping, the SLDS component library is available in Figma."},
        {title:"Clickable Prototypes",desc:"Interactive prototypes let users navigate between screens, revealing usability issues before any code is written — a click-through prototype is more valuable than a static mockup for testing."},
        {title:"Prototype Testing",desc:"Run usability sessions with clickable prototypes by asking users to complete representative tasks — observe hesitation, errors, and confusion rather than asking if they like the design."}
      ]},
      {name:"Testing",pct:13,color:"#1ABC9C",desc:"Plan and run usability tests and interpret findings to improve Salesforce designs.",keyTopics:[
        {title:"Usability Testing",desc:"Moderated and unmoderated usability tests identify where users struggle with a design — 5 users typically reveal 85% of usability problems."},
        {title:"A/B Testing",desc:"A/B tests compare two design variants with real users under controlled conditions — best used for optimizing specific interactions with measurable outcomes."},
        {title:"Heuristic Evaluation",desc:"Heuristic evaluation uses Nielsen's 10 usability heuristics to identify design problems without users — faster than usability testing but less representative."},
        {title:"Interpreting Results",desc:"Synthesize test findings into prioritized recommendations — separate symptoms (what users did) from root causes (why) to propose the right design solutions."}
      ]},
      {name:"Accessibility",pct:15,color:"#BDC3E7",desc:"Design Salesforce experiences that meet WCAG accessibility standards and work for users with diverse abilities.",keyTopics:[
        {title:"WCAG 2.1 Principles",desc:"Perceivable, Operable, Understandable, Robust (POUR) — WCAG 2.1 AA is the required accessibility standard for Salesforce Lightning components and custom apps."},
        {title:"Colour Contrast",desc:"Text must meet a 4.5:1 contrast ratio with its background (3:1 for large text) — use SLDS design tokens which are pre-validated for contrast compliance."},
        {title:"Keyboard Navigation",desc:"All interactive elements must be reachable and operable via keyboard alone — test with Tab, Shift+Tab, Enter, Space, and arrow keys to verify focus order and trap avoidance."},
        {title:"Screen Reader Support",desc:"Use semantic HTML, ARIA roles, labels, and alt text so screen readers can convey meaning — SLDS components include built-in ARIA attributes but custom components need manual review."}
      ]}
    ],
    studyDays:[
      {tag:"ux-fundamentals",focus:"UX fundamentals: user-centered design, personas, and accessibility standards",topics:[
        {text:"UX Designer Exam Guide",url:"https://trailhead.salesforce.com/help?article=Salesforce-Certified-User-Experience-Designer-Exam-Guide"},
        {text:"User-Centered Design Trailhead",url:"https://trailhead.salesforce.com/content/learn/modules/ux-designer"},
        {text:"WCAG Accessibility Guidelines",url:"https://www.w3.org/WAI/standards-guidelines/wcag/"},
        {text:"Salesforce Accessibility Standards",url:"https://help.salesforce.com/s/articleView?id=sf.accessibility_overview.htm"},
        {text:"UX Designer Trailmix",url:"https://trailhead.salesforce.com/users/strailhead/trailmixes/prepare-for-your-salesforce-user-experience-designer-credential"},
        {text:"Salesforce Design System (SLDS)",url:"https://www.lightningdesignsystem.com/"}
      ]},
      {tag:"slds-lightning",focus:"Salesforce Lightning Design System: tokens, components, and design patterns",topics:[
        {text:"Lightning Design System Overview",url:"https://www.lightningdesignsystem.com/"},
        {text:"SLDS Components",url:"https://www.lightningdesignsystem.com/components/overview/"},
        {text:"SLDS Design Tokens",url:"https://www.lightningdesignsystem.com/design-tokens/"},
        {text:"SLDS Patterns",url:"https://www.lightningdesignsystem.com/patterns/"},
        {text:"LWC and SLDS",url:"https://developer.salesforce.com/docs/platform/lwc/guide/create-components-css.html"},
        {text:"Dynamic Forms and Dynamic Actions",url:"https://help.salesforce.com/s/articleView?id=sf.dynamic_forms_overview.htm"}
      ]},
      {tag:"declarative-ux",focus:"Declarative UX tooling: Lightning App Builder, Global Actions, and page templates",topics:[
        {text:"Lightning App Builder",url:"https://help.salesforce.com/s/articleView?id=sf.lightning_app_builder_overview.htm"},
        {text:"Page Templates",url:"https://help.salesforce.com/s/articleView?id=sf.lightning_app_builder_templates.htm"},
        {text:"Global Actions",url:"https://help.salesforce.com/s/articleView?id=sf.actions_overview.htm"},
        {text:"Quick Actions",url:"https://help.salesforce.com/s/articleView?id=sf.actions_overview_quick.htm"},
        {text:"In-App Guidance",url:"https://help.salesforce.com/s/articleView?id=sf.customhelp_lex_prompt_parent.htm"},
        {text:"Utility Bar",url:"https://help.salesforce.com/s/articleView?id=sf.lightning_app_builder_utility_overview.htm"}
      ]},
      {tag:"exam-prep-ux",focus:"UX Designer exam prep: SLDS, accessibility, user-centered design, and Lightning pages",topics:[
        {text:"UX Designer Exam Guide",url:"https://trailhead.salesforce.com/help?article=Salesforce-Certified-User-Experience-Designer-Exam-Guide"},
        {text:"UX Designer Trailmix",url:"https://trailhead.salesforce.com/users/strailhead/trailmixes/prepare-for-your-salesforce-user-experience-designer-credential"},
        {text:"Lightning Design System",url:"https://www.lightningdesignsystem.com/"},
        {text:"Accessibility Specialist Superbadge",url:"https://trailhead.salesforce.com/content/learn/superbadges/superbadge_accessibility"},
        {text:"UX Designer Module",url:"https://trailhead.salesforce.com/content/learn/modules/ux-designer"},
        {text:"Exam Registration",url:"https://trailheadacademy.salesforce.com/certificate/exam-ux-designer---Plat-Des-201"}
      ]}
    ],
    quiz:[
      {domain:"Salesforce Lightning Design System",q:"Which SLDS resource provides the HTML and CSS reference implementation for a specific UI component?",opts:["Design tokens","Component blueprint","Utility class","Icon library"],correct:1,explanation:"Component blueprints are the SLDS reference implementations — they show the exact HTML structure and CSS classes needed to build each component correctly and accessibly."},
      {domain:"Salesforce Lightning Design System",q:"What is the purpose of SLDS design tokens?",opts:["To define component behaviour with JavaScript","To store named visual properties (colours, spacing, font sizes) that ensure consistency across components","To generate SOQL queries for styling data","To configure page layout assignments"],correct:1,explanation:"Design tokens are named variables for visual properties — using them instead of hardcoded values ensures visual consistency and makes global theme changes easy to propagate."},
      {domain:"Accessibility",q:"What is the minimum colour contrast ratio required for normal-size body text to meet WCAG 2.1 AA?",opts:["2:1","3:1","4.5:1","7:1"],correct:2,explanation:"WCAG 2.1 AA requires a minimum 4.5:1 contrast ratio for normal text (below 18pt or 14pt bold) and 3:1 for large text."},
      {domain:"Accessibility",q:"Which ARIA attribute provides an accessible name to an icon button that has no visible text label?",opts:["aria-role","aria-label","aria-hidden","aria-required"],correct:1,explanation:"aria-label provides an accessible name for elements without visible text — screen readers announce this label instead of nothing when the user focuses the button."},
      {domain:"Discovery",q:"A UX designer needs to understand how field sales reps currently use the Salesforce mobile app in the field. Which research method is most appropriate?",opts:["A/B testing","Contextual inquiry (field observation)","Heuristic evaluation","Analytic snapshot report"],correct:1,explanation:"Contextual inquiry involves observing users in their actual work environment — it reveals real behaviours and workarounds that interviews alone would not surface."},
      {domain:"Discovery",q:"Which output best communicates the emotional journey a customer takes when interacting with support across multiple channels?",opts:["Entity-relationship diagram","Customer journey map","SLDS component blueprint","Process flow diagram"],correct:1,explanation:"A customer journey map visualizes the end-to-end experience across touchpoints, including emotional highs and lows, pain points, and opportunities for improvement."},
      {domain:"UX Fundamentals",q:"A Salesforce record page is overwhelming sales reps with too many fields at once. Which UX principle should the designer apply?",opts:["Visual hierarchy","Consistency","Progressive disclosure","Affordance"],correct:2,explanation:"Progressive disclosure reduces cognitive load by showing only the information users need at each step — tabs, related lists, and expandable sections implement this principle in Salesforce."},
      {domain:"UX Fundamentals",q:"Which UX principle does a save button that changes colour when a form is complete exemplify?",opts:["Progressive disclosure","Affordance","Feedback","Error prevention"],correct:2,explanation:"Feedback communicates the result of user actions — the button changing colour tells the user their input has been recognised and the action is now available."},
      {domain:"Prototyping",q:"A designer needs to quickly validate the structure and navigation of a new Salesforce app before investing in visual design. Which prototype fidelity is most appropriate?",opts:["High-fidelity interactive prototype","Animated Apex-powered prototype","Low-fidelity wireframe","Production sandbox demo"],correct:2,explanation:"Low-fidelity wireframes test structure and flow cheaply and quickly — they are appropriate early in the design process when the goal is to validate information architecture, not visual design."},
      {domain:"Prototyping",q:"What is the primary advantage of a clickable prototype over a static mockup during user testing?",opts:["It can be deployed to a production org","It allows testers to navigate and interact, revealing usability issues with flow and transitions","It is quicker to create than a wireframe","It validates business logic and data integrity"],correct:1,explanation:"Clickable prototypes let users navigate between screens as they would in the real product — this reveals confusion about navigation, flow, and affordances that static images cannot surface."},
      {domain:"Testing",q:"A designer runs a usability test with 5 participants. According to Jakob Nielsen's research, approximately what percentage of usability problems should this reveal?",opts:["25%","50%","85%","100%"],correct:2,explanation:"Nielsen's research shows that 5 users reveal approximately 85% of usability problems — this is why small-sample usability testing is considered cost-effective and is the standard recommendation."},
      {domain:"Testing",q:"During usability testing, a participant repeatedly tries to click a graphic that is not interactive. What does this indicate?",opts:["The participant lacks Salesforce training","The graphic has a false affordance — it looks clickable but is not","The page layout needs more fields","The font size is too small"],correct:1,explanation:"A false affordance is when a visual element looks interactive but is not — this is a design problem, not a user error. The graphic needs to be redesigned to not suggest interactivity."},
      {domain:"Salesforce Lightning Design System",q:"An LWC developer uses inline CSS instead of SLDS utility classes for spacing. What is the main concern with this approach?",opts:["Inline CSS is not supported in LWC","It will break the component in mobile view","It bypasses SLDS design tokens, creating inconsistency and making future theme changes harder","It violates governor limits"],correct:2,explanation:"SLDS utility classes use design tokens under the hood — bypassing them with hardcoded inline styles creates visual inconsistency and means the component won't respond to theme or branding changes."},
      {domain:"Accessibility",q:"Which keyboard key should move focus to the next interactive element in a Salesforce form?",opts:["Enter","Space","Tab","Escape"],correct:2,explanation:"Tab moves focus forward through interactive elements in DOM order — all Salesforce components and custom LWC components must support this keyboard pattern for accessibility compliance."},
      {domain:"Discovery",q:"Which artifact synthesizes user research findings into a fictional but realistic representation of a user group's goals, behaviours, and frustrations?",opts:["Journey map","Persona","Wireframe","Affinity diagram"],correct:1,explanation:"Personas are research-backed representations of user archetypes — they synthesize patterns from user research into a character designers can empathize with and make decisions on behalf of."},
      {domain:"UX Fundamentals",q:"A company wants their custom Salesforce app to feel like a native part of the platform so users don't have to relearn conventions. Which principle does this exemplify?",opts:["Affordance","Consistency","Progressive disclosure","Error prevention"],correct:1,explanation:"Consistency means following established conventions so users can apply existing knowledge — building with SLDS and following Salesforce patterns makes custom apps feel native and reduces the learning curve."},
      {domain:"Accessibility",q:"An icon-only button needs to be accessible to screen reader users. Which attribute should be added?",opts:["role='button'","tabindex='0'","aria-label with a descriptive name","alt text on the button element"],correct:2,explanation:"aria-label provides an accessible name for the button that screen readers announce — without it, a screen reader would only say 'button' with no context about what it does."},
      {domain:"Testing",q:"What is heuristic evaluation?",opts:["Testing with 5 or more real users","An expert review of a design against established usability principles","An A/B test comparing two design variants","Automated accessibility scanning"],correct:1,explanation:"Heuristic evaluation is an expert review where evaluators assess a design against recognized usability principles (like Nielsen's 10 heuristics) to identify problems without recruiting real users."},
      {domain:"Salesforce Lightning Design System",q:"When should a designer use the SLDS Figma component library?",opts:["When deploying LWC components to production","When creating high-fidelity prototypes or mockups that accurately represent Salesforce UI","When writing Apex test classes","When configuring permission sets"],correct:1,explanation:"The SLDS Figma component library contains pre-built SLDS components for design tools — using it ensures mockups and prototypes accurately represent how the final Salesforce UI will look."},
      {domain:"UX Fundamentals",q:"Which information architecture technique groups navigation items by how users think about tasks, rather than by internal system categories?",opts:["Card sorting","Heuristic evaluation","Affinity diagramming","A/B testing"],correct:0,explanation:"Card sorting is an IA research technique where users group topics into categories that make sense to them — the results reveal user mental models and should drive Salesforce app navigation structure."}
    ],
    tips:[
      {icon:"🎨",title:"SLDS Is the Core Domain",body:"The Lightning Design System domain has the highest weight. Know components, design tokens, utility classes, and icons thoroughly — including when to use each and the accessibility requirements for each."},
      {icon:"♿",title:"Accessibility Is Heavily Tested",body:"Know WCAG 2.1 AA requirements, especially colour contrast ratios (4.5:1 for normal text, 3:1 for large text), keyboard navigation patterns, ARIA roles and labels, and screen reader support."},
      {icon:"🔍",title:"Match Research Method to Question",body:"Scenario questions will describe a design challenge — know which research method (interview, survey, usability test, heuristic evaluation, card sort) is most appropriate for each situation."},
      {icon:"📐",title:"Know Fidelity Trade-offs",body:"Understand when to use low-fi wireframes vs high-fi prototypes — the exam tests your ability to choose the right tool for the design question being answered at each stage of a project."},
      {icon:"🧭",title:"Apply UX Principles to Salesforce",body:"Questions often describe a Salesforce-specific scenario and ask which UX principle applies. Map principles (progressive disclosure, affordance, consistency, feedback) to specific Salesforce features."},
      {icon:"🗣️",title:"Study the Exam Guide",body:"Download the official UX Designer exam guide from Trailhead — it lists exact domain weights so you know where to focus. The SLDS and Accessibility domains together account for 40% of the exam."},
      {icon:"🖼️",title:"Explore SLDS in Figma",body:"Use the SLDS Figma component library to practice prototyping — hands-on experience with SLDS components will make blueprint and token questions much more intuitive on exam day."}
    ]
  },

  "Platform Strategy Designer": {
    questions: 60,
    time: 105,
    pass: "65%",
    experience: "2+ years",
    trailheadUrl: "https://trailheadacademy.salesforce.com/certificate/exam-strategy-designer---Plat-UX-102",
    prerequisites: [
      {name:"Platform Administrator",url:"https://developer.salesforce.com/docs/platform/lwc/guide/data-ui-api.html",note:"Understanding the Salesforce platform's capabilities is essential for advising clients on org strategy."}
    ],
    overview: "The Platform Strategy Designer certification validates your ability to advise customers on how to get maximum value from Salesforce through sound org strategy, business process alignment, and change management. The exam tests your skills in discovery, requirements analysis, solution scoping, governance, and measuring platform ROI — making it ideal for solution architects and business-focused consultants.",
    domains: [
      {name:"Customer Discovery",pct:22,color:"#00A1E0",desc:"Conduct discovery sessions to understand business goals, constraints, and stakeholder needs before recommending solutions.",keyTopics:[
        {title:"Discovery Frameworks",desc:"Use structured discovery frameworks (5W1H, value stream mapping, business capability modeling) to surface the real business problem behind a feature request."},
        {title:"Stakeholder Mapping",desc:"Identify all stakeholders — executive sponsors, end users, IT, compliance — and understand their goals, concerns, and influence before designing a solution."},
        {title:"Current State Assessment",desc:"Document the as-is process, systems, data flows, and pain points before designing the future state — jumping to solutions without this leads to misaligned implementations."},
        {title:"Business Goal Alignment",desc:"Map every solution recommendation back to a measurable business outcome — features without a business case are scope creep, not value creation."},
        {title:"Constraint Identification",desc:"Surface technical, budgetary, organizational, and regulatory constraints early — these constraints should shape the solution, not be discovered after design is complete."}
      ]},
      {name:"Business Analysis",pct:18,color:"#2ECC71",desc:"Translate business requirements into actionable Salesforce solution specifications using recognized analysis techniques.",keyTopics:[
        {title:"User Stories and Acceptance Criteria",desc:"Write user stories in 'As a [user], I want [goal], so that [benefit]' format with clear, testable acceptance criteria — vague stories lead to misbuilt features."},
        {title:"Process Mapping",desc:"Use swimlane diagrams, flowcharts, and BPMN notation to document business processes — process maps reveal handoffs, bottlenecks, and automation opportunities."},
        {title:"Gap Analysis",desc:"Compare current capabilities against desired future state to scope the implementation — a gap analysis makes the work visible and enables realistic project planning."},
        {title:"Prioritization Frameworks",desc:"Use MoSCoW (Must, Should, Could, Won't), effort/impact matrices, or weighted scoring to help stakeholders make trade-off decisions on scope."}
      ]},
      {name:"Salesforce Solution Strategy",pct:25,color:"#F39C12",desc:"Recommend the right Salesforce products, features, and configuration approaches to meet business requirements.",keyTopics:[
        {title:"Declarative vs Programmatic",desc:"Always default to declarative solutions (Flow, validation rules, formula fields) over Apex code — they are cheaper to build, easier to maintain, and don't require a developer to change."},
        {title:"Org Strategy Decisions",desc:"Multi-org vs single org, sandbox strategy, data model decisions, and integration architecture are all org-strategy decisions with long-term consequences — get them right in design."},
        {title:"Product Selection",desc:"Recommend the right Salesforce cloud and edition for the business need — Sales Cloud, Service Cloud, Experience Cloud, and Marketing Cloud each solve different problems."},
        {title:"Phasing and MVP",desc:"Phase implementations to deliver value early — an MVP with the highest-impact features in phase 1 is more valuable than a 12-month big-bang delivery."},
        {title:"Build vs Buy",desc:"AppExchange managed packages often solve common problems faster than custom builds — evaluate total cost of ownership, upgrade risk, and fit before recommending custom development."}
      ]},
      {name:"Governance and Change Management",pct:20,color:"#E74C3C",desc:"Establish governance structures and change management plans that ensure adoption and long-term platform success.",keyTopics:[
        {title:"Centre of Excellence",desc:"A Salesforce CoE owns standards, architecture decisions, developer governance, and platform roadmap — establishing one early prevents technical debt and inconsistent implementations."},
        {title:"Change Management Principles",desc:"Adoption doesn't happen automatically — change management requires communication, training, executive sponsorship, and feedback loops to move users from awareness to proficiency."},
        {title:"Release Management",desc:"Define a release cadence, change approval process, and sandbox strategy — unmanaged change leads to broken integrations, data quality issues, and user frustration."},
        {title:"Training Strategy",desc:"Design role-based training plans that meet users where they are — generic 'how to use Salesforce' training fails; task-based training tied to real workflows succeeds."}
      ]},
      {name:"Measuring Business Value",pct:15,color:"#1ABC9C",desc:"Define KPIs, success metrics, and measurement strategies to demonstrate and maximize Salesforce ROI.",keyTopics:[
        {title:"KPI Definition",desc:"KPIs must be specific, measurable, and tied to the business outcome the Salesforce implementation is designed to achieve — vanity metrics (logins, records created) don't prove ROI."},
        {title:"Baseline Measurement",desc:"Establish baseline metrics before go-live so post-implementation improvements can be quantified — without a baseline, you cannot prove the system delivered value."},
        {title:"Leading vs Lagging Indicators",desc:"Leading indicators (pipeline coverage, daily active users) predict future outcomes; lagging indicators (revenue, case resolution rate) confirm past performance — track both."},
        {title:"ROI Calculation",desc:"Calculate ROI by comparing cost of implementation and operation against quantified business benefits (time saved, revenue increased, cost reduced) over a defined period."}
      ]}
    ],
    studyDays:[
      {tag:"strategy-design",focus:"Salesforce strategy design: discovery, business analysis, and solution blueprinting",topics:[
        {text:"Strategy Designer Exam Guide",url:"https://trailhead.salesforce.com/help?article=Salesforce-Certified-Strategy-Designer-Exam-Guide"},
        {text:"Strategy Designer Trailmix",url:"https://trailhead.salesforce.com/users/strailhead/trailmixes/prepare-for-your-salesforce-strategy-designer-credential"},
        {text:"Business Analysis Trailhead",url:"https://trailhead.salesforce.com/content/learn/modules/salesforce-business-analyst-quick-look"},
        {text:"Customer Journey Mapping",url:"https://trailhead.salesforce.com/content/learn/modules/ux-designer"},
        {text:"Human-Centered Design",url:"https://trailhead.salesforce.com/content/learn/modules/ux-designer"},
        {text:"Salesforce Architect Patterns",url:"https://architect.salesforce.com/design/patterns"}
      ]},
      {tag:"exam-prep-strategy",focus:"Strategy Designer exam prep: discovery, blueprinting, and solution design scenarios",topics:[
        {text:"Strategy Designer Exam Guide",url:"https://trailhead.salesforce.com/help?article=Salesforce-Certified-Strategy-Designer-Exam-Guide"},
        {text:"Strategy Designer Trailmix",url:"https://trailhead.salesforce.com/users/strailhead/trailmixes/prepare-for-your-salesforce-strategy-designer-credential"},
        {text:"Business Analyst Module",url:"https://trailhead.salesforce.com/content/learn/modules/salesforce-business-analyst-quick-look"},
        {text:"UX Design Module",url:"https://trailhead.salesforce.com/content/learn/modules/ux-designer"},
        {text:"Exam Registration",url:"https://trailheadacademy.salesforce.com/certificate/exam-strategy-designer---Plat-Des-202"},
        {text:"Salesforce Architect Website",url:"https://architect.salesforce.com"}
      ]}
    ],
    quiz:[
      {domain:"Customer Discovery",q:"During discovery, a stakeholder requests a complex custom feature. What should a strategy designer do first?",opts:["Build the feature in a sandbox to test it","Ask clarifying questions to understand the business problem the feature is trying to solve","Check if the feature is available on AppExchange","Decline the request and propose an MVP"],correct:1,explanation:"Strategy designers should always understand the underlying business problem before evaluating solutions — the feature requested may not be the best solution to the actual problem."},
      {domain:"Customer Discovery",q:"Which artifact maps all stakeholders, their roles, their goals, and their level of influence on a Salesforce implementation?",opts:["Process flow diagram","RACI matrix","Stakeholder map","Journey map"],correct:2,explanation:"A stakeholder map identifies who is involved, their interests, influence, and how they should be engaged — it is essential for managing communication and gaining buy-in throughout a project."},
      {domain:"Business Analysis",q:"Which user story format is considered best practice?",opts:["'The system should allow users to create cases'","'As a service agent, I want to create cases from email so that customer issues are tracked automatically'","'Create a case creation feature for service agents'","'Service agents need case creation capability — high priority'"],correct:1,explanation:"The 'As a [user], I want [goal], so that [benefit]' format captures who needs the feature, what they need, and why — this context prevents scope creep and enables better acceptance criteria."},
      {domain:"Business Analysis",q:"A company's current process requires managers to manually approve discount requests over 20%. Which Salesforce feature directly addresses this process?",opts:["Validation rule","Approval process","Record-triggered flow","Assignment rule"],correct:1,explanation:"Approval processes route records through a defined multi-step approval chain based on criteria — this directly replaces a manual approval workflow with an automated, tracked process."},
      {domain:"Salesforce Solution Strategy",q:"A customer wants a solution to automatically log emails from Outlook to Salesforce Contacts. What is the best declarative approach?",opts:["Write Apex triggers on the Email object","Use Einstein Activity Capture or an Outlook Integration managed package","Build a custom LWC email logger","Create a scheduled Flow that queries the email server"],correct:1,explanation:"Einstein Activity Capture and the Salesforce Outlook/Gmail integration are declarative, native solutions for email sync — recommending them avoids unnecessary custom development."},
      {domain:"Salesforce Solution Strategy",q:"A client asks you to build a complex custom CPQ solution from scratch. What should you evaluate first?",opts:["Hire a developer team","Evaluate AppExchange managed package options for CPQ","Recommend a multi-org strategy","Build a prototype in a scratch org"],correct:1,explanation:"Before custom building, a strategy designer should evaluate whether AppExchange packages (like Salesforce CPQ) can solve the problem faster and with lower long-term maintenance cost."},
      {domain:"Salesforce Solution Strategy",q:"Which principle should guide a strategy designer when choosing between Flow Builder automation and Apex code?",opts:["Always use Apex because it is more powerful","Default to declarative (Flow) solutions first — use Apex only when declarative tools cannot meet the requirement","Use Apex for anything involving more than 3 conditions","Flow is only appropriate for screen flows, not record automation"],correct:1,explanation:"Clicks-before-code is a core Salesforce design principle — declarative solutions are cheaper to build, easier to maintain, and don't require a developer to modify, making them the preferred default."},
      {domain:"Governance and Change Management",q:"What is the primary purpose of a Salesforce Centre of Excellence (CoE)?",opts:["To replace the IT department","To own platform standards, architecture decisions, and governance — ensuring consistent and scalable Salesforce implementations","To manage Salesforce user licenses","To develop all custom Apex code"],correct:1,explanation:"A CoE provides organizational governance for the Salesforce platform — it sets standards, owns the platform roadmap, reviews new development, and prevents inconsistency and technical debt."},
      {domain:"Governance and Change Management",q:"A Salesforce rollout has high executive support but low end-user adoption after go-live. What is the most likely root cause?",opts:["The org has too many custom objects","The system has performance issues","Change management and user training were insufficient","The wrong Salesforce edition was purchased"],correct:2,explanation:"Executive sponsorship alone doesn't drive adoption — users need awareness, desire, knowledge, ability, and reinforcement (ADKAR). Low adoption after go-live typically indicates inadequate training and change management."},
      {domain:"Measuring Business Value",q:"Before a Salesforce implementation goes live, what must be in place to prove ROI afterwards?",opts:["A sandbox copy of the production org","Baseline measurements of the KPIs the implementation is intended to improve","A full data backup","Signed acceptance testing documents"],correct:1,explanation:"Without baseline measurements before go-live, you cannot quantify improvement after — establishing baselines is a prerequisite for proving ROI and is often overlooked in project planning."},
      {domain:"Measuring Business Value",q:"A company measures Salesforce success by counting total records created. Why is this a poor KPI?",opts:["Salesforce does not track record creation","It is a vanity metric — it does not measure whether the system is delivering business outcomes","Record count is not reportable in dashboards","It is too expensive to measure accurately"],correct:1,explanation:"Vanity metrics (logins, records, page views) measure activity but not outcomes — meaningful KPIs must connect to business results like faster case resolution, increased revenue, or reduced cost."},
      {domain:"Customer Discovery",q:"A stakeholder insists on a feature that conflicts with the recommended solution architecture. What is the best response?",opts:["Build the feature as requested to maintain the relationship","Document the risk, present trade-offs, and let the stakeholder make an informed decision","Escalate to the project sponsor immediately","Reject the request and move forward with the recommended approach"],correct:1,explanation:"Strategy designers are advisors, not order-takers — the right approach is to present the risks and trade-offs so the stakeholder can make an informed decision, then document it either way."},
      {domain:"Governance and Change Management",q:"Which change management model uses Awareness, Desire, Knowledge, Ability, and Reinforcement as its stages?",opts:["Kotter 8-Step","ADKAR (Prosci)","RACI","PRINCE2"],correct:1,explanation:"ADKAR is the Prosci change management model — it provides a framework for understanding and managing the individual change journey from awareness through to sustained adoption."},
      {domain:"Salesforce Solution Strategy",q:"A company has 3 separate business units with very different data models and security requirements. Which org strategy consideration is most important?",opts:["Whether to use sandbox or scratch orgs","Whether a single org with business units or separate orgs better serves the business — considering data sharing, integration complexity, and cost","Which Salesforce edition to purchase","Whether to use Flow or Apex for automation"],correct:1,explanation:"Multi-org vs single-org is a strategic architecture decision — separate orgs provide full data isolation but increase integration complexity and licensing cost; single org simplifies sharing but requires careful design."},
      {domain:"Business Analysis",q:"Which prioritization framework categorizes requirements as Must have, Should have, Could have, and Won't have?",opts:["RACI","MoSCoW","Kano model","INVEST"],correct:1,explanation:"MoSCoW prioritization helps stakeholders make explicit scope trade-offs — it is widely used in Salesforce projects to distinguish essential features from nice-to-haves and out-of-scope items."},
      {domain:"Measuring Business Value",q:"Which type of metric predicts future business performance rather than measuring past results?",opts:["Lagging indicator","Vanity metric","Leading indicator","Baseline metric"],correct:2,explanation:"Leading indicators (like pipeline coverage ratio or daily active user counts) predict future outcomes — they are actionable because you can influence them before it's too late, unlike lagging indicators."},
      {domain:"Customer Discovery",q:"A business analyst has documented a current-state process map. What should be built next before designing the Salesforce solution?",opts:["The full data model","A future-state process map with Salesforce features annotated on the flow","A deployment plan","An AppExchange evaluation checklist"],correct:1,explanation:"A future-state process map shows how the business will operate after implementation — it bridges discovery and solution design by showing where Salesforce features fit into the redesigned workflow."},
      {domain:"Governance and Change Management",q:"A company wants to ensure all Salesforce changes go through a review before reaching production. Which governance tool supports this?",opts:["Approval process","A Salesforce CoE with a change review board and sandbox-first deployment policy","Permission set groups","Platform encryption"],correct:1,explanation:"A CoE with a change review board enforces the governance process — all changes should be built and tested in sandbox, reviewed for compliance with standards, then promoted through a defined release process."},
      {domain:"Salesforce Solution Strategy",q:"A company's first Salesforce implementation is 18 months of scope. What should a strategy designer recommend?",opts:["Proceed with the full 18-month scope to deliver complete value","Phase the implementation with an MVP in the first 3 months to deliver early value and reduce risk","Reduce the scope to 6 months by removing all custom development","Build everything in a developer edition org first"],correct:1,explanation:"Phasing with an MVP delivers value sooner, enables user feedback before full commitment, and reduces the risk of an 18-month implementation delivering something users don't want."},
      {domain:"Business Analysis",q:"An acceptance criterion states 'The system should be fast'. Why is this poorly written?",opts:["It is too short","It is not testable or measurable — a good criterion would specify 'page loads within 2 seconds for 99% of requests'","It should be written as a user story instead","It describes a technical constraint, not a business requirement"],correct:1,explanation:"Acceptance criteria must be testable — vague criteria like 'fast', 'user-friendly', or 'accurate' cannot be objectively evaluated. Always make acceptance criteria specific and measurable."}
    ],
    tips:[
      {icon:"🧭",title:"Think Like a Consultant",body:"Every question is a scenario where you advise a customer. Ask yourself: what is the real business problem? What is the right Salesforce recommendation? Always connect recommendations to business outcomes."},
      {icon:"🔑",title:"Clicks Before Code",body:"When asked to choose between declarative and programmatic solutions, default to declarative (Flow, validation rules, formula fields) unless the scenario clearly requires Apex. This is a core exam principle."},
      {icon:"📋",title:"Discovery Before Design",body:"The exam consistently tests that discovery (understanding the problem) must happen before solution design. If a question gives a scenario without enough context, the answer is usually 'gather more information first.'"},
      {icon:"🏛️",title:"Governance Means CoE",body:"Questions about ensuring consistent, scalable Salesforce implementations point to a Centre of Excellence. Know the CoE's responsibilities: standards, governance, roadmap, review gates, and training."},
      {icon:"📊",title:"KPIs Need Baselines",body:"Any question about measuring Salesforce ROI or success should include establishing a baseline before go-live. You cannot prove improvement without knowing the starting point."},
      {icon:"🔄",title:"Change Management Is Not Optional",body:"Low adoption is a change management failure, not a technology failure. Know ADKAR and the types of change management interventions (communication, training, sponsorship, reinforcement) and when each applies."},
      {icon:"🏆",title:"Study the Exam Guide Closely",body:"The Strategy Designer exam guide lists domain weights — Customer Discovery (22%), Solution Strategy (25%), and Governance (20%) are the heaviest domains. Allocate your study time accordingly."}
    ]
  },

});
